---
apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: pac-app
  annotations:
    pipelinesascode.tekton.dev/on-event: "[pull_request]"
    pipelinesascode.tekton.dev/on-target-branch: "main"
    pipelinesascode.tekton.dev/max-keep-runs: "5"
spec:
  pipelineSpec:
    tasks:
      - name: noop-task
        workspaces:
          - name: source
            workspace: source
        taskSpec:
          workspaces:
            - name: source
          steps:
            - name: noop-task
              image: registry.access.redhat.com/ubi8/ubi-micro:8.5
              workingDir: $(workspaces.source.path)
              script: |
                sleep 30
                exit 1
